### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by ff202118** [SinHanYang/Dual-CAN#2]
COAID.  
Where are 'NewsRealCOVID-19_tweets_expanded.csv' and 'NewsFakeCOVID-19_tweets_expanded.csv'  from?
I can't find them in the https://github.com/cuilimeng/CoAID.  I guess they are NewsFakeCOVID-19_tweets.csv and  NewsRealCOVID-19_tweets.csv, but there are not column named 'full_text' in them.

**Comment by ff202118** [comment]
Sorry, I haven't read the paper carefully; I already know.

**Comment by Rogerskelamen** [comment]
@ff202118 
Hi, I encounter the same problem that I can't find NewsRealCOVID-19_tweets_expanded.csv. Can you point out where the paper mention the dataset about it? Great appreciate if you could reply to help me out.

**Comment by ff202118** [comment]
> @ff202118您好，我遇到了同样的问题，找不到 NewsRealCOVID-19_tweets_expanded.csv。你能指出论文在哪里提到了它的数据集吗？如果您能回复帮助我，我将不胜感激。

In the appendix of the paper under "A Dataset," the authors have provided the links to the datasets, from which you can attempt to download them.

**Comment by Rogerskelamen** [comment]
Oh, I see. Though I still want to know how to generate json dataset from https://github.com/cuilimeng/CoAID. Anyway, thanks for helping.
