### ISSUE TITLE
device

### ISSUE THREAD

**Issue by ff202118** [SinHanYang/Dual-CAN#3]
I'd like to know what device you used for training? My device is Tesla T4(16GB)
I encountered some issues during my training, as shown in the image.

![image](https://github.com/SinHanYang/Dual-CAN/assets/101726840/9f5e6693-79fa-4971-8354-41decc293ee0)
My device is Tesla T4(16GB)

**Comment by SinHanYang** [comment]
Hi, Thanks for reaching out! I used RTX A6000 for experiments. Perhaps you can try smaller batch size for your device.

**Comment by ff202118** [comment]
Thank you for your response. I have successfully resolved this issue. I appreciate your work in fake news detection.


万俟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SinHanYang/Dual-CAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月25日(星期三) 中午12:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SinHanYang/Dual-CAN] device (Issue #3)





 
Hi, Thanks for reaching out! I used RTX A6000 for experiments. Perhaps you can try smaller batch size for your device.
