### ISSUE TITLE
datatset

### ISSUE THREAD

**Issue by chentaorui** [SinHanYang/Dual-CAN#4]
I hope this email finds you well. My name is ChenTaoRui, and I am a graduate student at the University of Electronic Science and Technology of China, currently conducting research on fake news detection.
﻿
I recently came across your paper and found it highly relevant and insightful for my research. I am particularly interested in reproducing the results presented in your paper to further understand and build upon your work.
﻿
I have accessed the code provided in your GitHub repository (https://github.com/SinHanYang/Dual-CAN/tree/main). However, I noticed that the dataset required to run the experiments is not included. Given the recent restrictions imposed by tagme on API access, I am unable to independently download the necessary data to recreate the dataset.
﻿
Therefore, I am writing to kindly request if you could share the dataset used in your study. Access to this dataset would be invaluable for my research, allowing me to accurately replicate your findings and contribute to the ongoing research in this field. I assure you that any data shared will be used strictly for academic purposes and in accordance with data privacy and ethical guidelines.
﻿
Thank you very much for your time and consideration. I look forward to your positive response.
﻿
Best regards

**Comment by SinHanYang** [comment]
Hi, Thanks for your interest in our work. The dataset link is in the [paper](https://aclanthology.org/2023.findings-eacl.7.pdf)'s Appendix.
